### PR TITLE
Guards against malformed trace extraction without allocating exceptions

### LINKED ISSUE #625: don't die or do expensive things on malformed input
We should add tests that malformed B3 headers don't throw, or if they do we catch it. This was identified in a related discussion about Jaeger's B3 codec.

Here, I think we should make a special hex parser that skips out on malformed (to differentiate it from null). This can log the failure at debug level as opposed to initializing an exception, throwing then catching that.

we should also benchmark malformed propagation to ensure we don't accidentally create overhead or miss parts. This should include extra field propagation and AWS

related issue https://github.com/jaegertracing/jaeger-client-java/issues/354

### PR DESCRIPTION
**Pull request by adriancole**
This makes sure when we parse bad data, we can log, but don't do things
expensive in the mean time. This does so by inlining parsing.

Fixes #625

### CODE REVIEW

**Comment by adriancole** [comment]
laptop says this can fail B3 73+ times per microsecond, so probably ok

File: brave/src/main/java/brave/propagation/B3Propagation.java [hunk 1]
```diff
@@ -115,35 +114,29 @@
...
-      result.spanId(lowerHexToUnsignedLong(spanId));
-      String parentSpanIdString = getter.get(carrier, propagation.parentSpanIdKey);
-      if (parentSpanIdString != null) result.parentId(lowerHexToUnsignedLong(parentSpanIdString));
-      return TraceContextOrSamplingFlags.create(result.build());
+      // Try to parse the span and parent ID into the context
+      if (result.parseSpanId(getter, carrier, propagation.spanIdKey)
+          && result.parseParentId(getter, carrier, propagation.parentSpanIdKey)) {
+        return TraceContextOrSamplingFlags.create(result.sampled(sampledV).debug(debug).build());
+      }
+      return TraceContextOrSamplingFlags.EMPTY; // trace context is malformed so return empty
```
Comment (jcchavezs) [inline brave/src/main/java/brave/propagation/B3Propagation.java]: So we don't even use the sample information if the parse of span/trace ID fail?

**Comment by adriancole** [comment]
If the trace context is malformed yeah I don't think there is value
trusting the sampling decision either. It is simpler this way and also
hopefully will help people find bugs.

**Comment by adriancole** [comment]
Keep in mind a well formed request is still good. Ex sampled without trace
id is ok. Only if a trace id is malformed should we kick out.

File: brave-tests/src/test/java/brave/propagation/B3PropagationTest.java [hunk 2]
```diff
@@ -48,4 +48,15 @@
     assertThat(result)
         .isEqualTo(SamplingFlags.NOT_SAMPLED);
   }
+
+  @Test public void extractTraceContext_malformed() {
+    MapEntry mapEntry = new MapEntry();
+    map.put("x-b3-traceid", "1"); // ok
```
Comment (jcchavezs) [inline brave-tests/src/test/java/brave/propagation/B3PropagationTest.java]: What about declaring more examples here on what happens by using a data provider? that would be more expressive in terms on which cases this will/won't fail. What do you think?

**Comment by adriancole** [comment]
backfilled tests including that it doesn't log by default

**Comment by adriancole** [comment]
>
> What about declaring more examples here on what happens by using a data
> provider? that would be more expressive in terms on which cases this
> will/won't fail. What do you think?
>
there's a fair amount of redundancy in the trace context tests vs here, so
was just testing lightly

>

**Comment by adriancole** [comment]
circleci is busted due to broken config on the bom which is fixed externally #628

**Comment by adriancole** [comment]
so benchmark results for extraction in normal case are almost exactly the same (within error range)

benchmark results for extracting a bad context are much different.


Scenario where there's a malformed parent ID, but everything else is OK (note: we toss the context based on malformed)

catch exception approach
```java
Benchmark                                    Mode  Cnt   Score   Error   Units
PropagationBenchmarks.extract_b3            thrpt   15  10.564 ± 0.469  ops/us
PropagationBenchmarks.extract_b3_malformed  thrpt   15   0.570 ± 0.027  ops/us
```

current code approach
```java
Benchmark                                    Mode  Cnt   Score   Error   Units
PropagationBenchmarks.extract_b3            thrpt   15  11.283 ± 0.424  ops/us
PropagationBenchmarks.extract_b3_malformed  thrpt   15  12.410 ± 0.380  ops/us
```

**Comment by llinder** [comment]
Nice test cases :)
