### PR TITLE
Makes HTTP request method mandatory

### LINKED ISSUE #1089: Escalate `HttpRequest.method()` as not nullable
While all other properties, possibly even path, could result in exceptions coerced to null, the HTTP method of the request should never end up null.

While there is a slight NPE risk in some implementations, I think it should be safe to enforce HTTP method (`HttpRequest.method()`) as not nullable. This allows one less null check on an extremely common path.

### PR DESCRIPTION
**Pull request by adriancole**
While all other properties can be absent or invalid, this makes the HTTP
method mandatory. This will help when we create a path to the request
from the response, as it allows chaining to the method without a null
check.

Note: Eventhough we've seen method incorrectly set in the past,
we've never seen it missing.

PS: While it seems path would also always be available even recently,
it isn't valid for all HTTP methods (ex OPTIONS and CONNECT). Also,
it can be null due to bad parsing (ex some things don't natively return
the path, only the URL). Also, it has been found missing before, most
recently due to a [request availablility bug](https://github.com/reactor/reactor-netty/pull/998) which is still not released! If we started enforcing path be present, it
would force a known set of scenarios to NPE causing people who can't
change their implementations to become revlocked until they can. This
makes forcing path to be not nullable, so late in the game, to be a cure
worse than the disease.

Fixes #1089

### CODE REVIEW

File: instrumentation/http/src/main/java/brave/http/HttpAdapter.java [hunk 1]
```diff
@@ -19,7 +19,7 @@
 /** @deprecated Since 5.10, use {@link HttpRequest} and {@link HttpResponse} */
 @Deprecated public abstract class HttpAdapter<Req, Resp> {
   /** @see HttpRequest#method() */
-  @Nullable public abstract String method(Req request);
+  public abstract String method(Req request);
 
   /** @see HttpRequest#path() */
   @Nullable public String path(Req request) {
```
Comment (anuraaga) [inline instrumentation/http/src/main/java/brave/http/HttpAdapter.java]: Agree that HTTP spec doesn't actually require a path (OPTIONS commonly has * which I don't know if we call a path, CONNECT has only authority). So nullable seems fine.

But not so sympathetic with the availability bug issue - seems like bad http library as opposed to bad instrumentation, not sure if that specifically should fall into our defensive requirements.

File: instrumentation/http/src/main/java/brave/http/HttpRequestParser.java [hunk 2]
```diff
@@ -62,8 +62,7 @@
     @Override public void parse(HttpRequest req, TraceContext context, SpanCustomizer span) {
       String name = spanName(req, context);
       if (name != null) span.name(name);
```
Comment (anuraaga) [inline instrumentation/http/src/main/java/brave/http/HttpRequestParser.java]: Think we can remove this null check (it's the one I most wanted to remove since it's the span name :) ).

But if you think we need it I guess we are missing `@Nullable` on the protected `spanName` method.

File: instrumentation/http/src/main/java/brave/http/HttpAdapter.java (hunk 1 above)
Comment (adriancole) [reply instrumentation/http/src/main/java/brave/http/HttpAdapter.java]: This was one example of path missing, something from last week, not the only time.

I think it is wise to be cautious as instrumentation should do no harm. Users can't always control versions of things and for example, even in armeria there are availability checks to prevent a known class of bugs. I don't expect you to agree with me but I disagree that we should just trust path will exist and anything that causes it not to be should crash requests.

File: instrumentation/http/src/main/java/brave/http/HttpRequestParser.java (hunk 2 above)
Comment (adriancole) [reply instrumentation/http/src/main/java/brave/http/HttpRequestParser.java]: I can fix the lack of nullable

File: instrumentation/http/src/main/java/brave/http/HttpAdapter.java (hunk 1 above)
Comment (adriancole) [reply instrumentation/http/src/main/java/brave/http/HttpAdapter.java]: I reworded the javadoc towards the method rationale without suggesting that's the only reason why. The other reasons could be in the class of parse failures, or availability drift outside our control, but IMHO shouldn't cause requests to crash. hope the words balance!

Comment (adriancole) [reply instrumentation/http/src/main/java/brave/http/HttpAdapter.java]: concretely, if we "fixed path" now, we'd definitely blow up former versions of instrumentation, causing revlock.

Comment (adriancole) [reply instrumentation/http/src/main/java/brave/http/HttpAdapter.java]: PS I'd be fine with forcing path to be present on the methods relevant in a major release. We'd just know this would invalidate third party stuff and they'd get revlocked to the old one, causing the old version to need patches in worst case. Not signing up for that work personally, but agree in a green field or known break scenario stricter rules could apply.

**Comment by adriancole** [comment]
added rationale because I think many people have not seen the horrors I have and wouldn't want anyone walking into a disaster by accident of less experience cc @openzipkin/core

**Comment by adriancole** [comment]
merging as #1086 rests on this assumption
