### PR TITLE
Prevents java.lang.NoClassDefFoundError when searching for platform

### LINKED ISSUE #599: Get NoClassDefFoundError of ThreadLocalRandom  when using jre6
when run in jre1.6.0_33，I got a exception:
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom
	at brave.internal.Platform.findPlatform(Platform.java:104)
	at brave.internal.Platform.<clinit>(Platform.java:27)
	at brave.Tracing$Builder.build(Tracing.java:271)

### PR DESCRIPTION
**Pull request by adriancole**
Recently, we added `Platform.nextTraceIdHigh()`, which compiled against
a JDK 7 type `ThreadLocalRandom` due to being indirectly referenced in
a utility method. This changes the signature such that it can't imply
this anymore.

This also removes AutoValue from platform as it adds unnecessary classes
to the jar.

Fixes #599

### CODE REVIEW

File: brave/src/main/java/brave/internal/Platform.java [hunk 1]
```diff
@@ -175,63 +172,81 @@ static Jre9 buildIfSupported(boolean zipkinV1Present) {
...
-    @IgnoreJRERequirement
-    @Override public long randomLong() {
-      return java.util.concurrent.ThreadLocalRandom.current().nextLong();
+    Jre9(boolean zipkinV1Present) {
+      super(zipkinV1Present);
     }
 
-    @IgnoreJRERequirement
-    @Override public long nextTraceIdHigh() {
-      return nextTraceIdHigh(java.util.concurrent.ThreadLocalRandom.current());
```
Comment (adriancole) [inline brave/src/main/java/brave/internal/Platform.java]: using a static method like this indirectly caused the code to compile against the TLR type, subverting the attempt to defer usage until runtime. I fixed the signature so that it couldn't do this anymore.

**Comment by adriancole** [comment]
try 4.14.2
