### PR TITLE
Fix: Kafka Streams partitioning

### LINKED ISSUE #942: Kafka Streams repartitioning
## Describe the Bug
The instrumentation of some Kafka Streams operations with KafkaStreamsTracing results in an unnecessary call to "KStream.transform ()". This can trigger unwanted and expensive repartitioning.
The operations involved are: filter(), filterNot(), peek(), and mark(). These operations return a TransformerSupplier where ValueTransformerWithKeySupplier would be more appropriate. The associated call to KStream.transformValues() will not mark the stream for a repartitioning.

## Steps to Reproduce

The following stream with Brave instrumentation generates 2 sub-topolgies : 

```
stream
	.filter((k, v) -> true)
	.transform(kafkaStreamsTracing.filter("spanName", (k, v) -> true))
	.join(table, (left, right) -> left)
	.to("output");
```

Produces the topology:

```
Topologies:
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000008 (topics: [KSTREAM-FILTER-0000000005-repartition])
      --> KSTREAM-JOIN-0000000009
    Processor: KSTREAM-JOIN-0000000009 (stores: [table-STATE-STORE-0000000000])
      --> KSTREAM-SINK-0000000010
      <-- KSTREAM-SOURCE-0000000008
    Source: KSTREAM-SOURCE-0000000001 (topics: [table])
      --> KTABLE-SOURCE-0000000002
    Sink: KSTREAM-SINK-0000000010 (topic: output)
      <-- KSTREAM-JOIN-0000000009
    Processor: KTABLE-SOURCE-0000000002 (stores: [table-STATE-STORE-0000000000])
      --> none
      <-- KSTREAM-SOURCE-0000000001

  Sub-topology: 1
    Source: KSTREAM-SOURCE-0000000003 (topics: [input])
      --> KSTREAM-TRANSFORM-0000000004
    Processor: KSTREAM-TRANSFORM-0000000004 (stores: [])
      --> KSTREAM-FILTER-0000000005
      <-- KSTREAM-SOURCE-0000000003
    Processor: KSTREAM-FILTER-0000000005 (stores: [])
      --> KSTREAM-FILTER-0000000007
      <-- KSTREAM-TRANSFORM-0000000004
    Processor: KSTREAM-FILTER-0000000007 (stores: [])
      --> KSTREAM-SINK-0000000006
      <-- KSTREAM-FILTER-0000000005
    Sink: KSTREAM-SINK-0000000006 (topic: KSTREAM-FILTER-0000000005-repartition)
      <-- KSTREAM-FILTER-0000000007
```

## Expected Behaviour
A single topology is expected like with the uninstrumented stream.

```
stream
	.filter((k, v) -> true)
	.join(table, (left, right) -> left)
	.to("output");
```

Produces the topolgy 

```
Topologies:
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000003 (topics: [input])
      --> KSTREAM-FILTER-0000000004
    Processor: KSTREAM-FILTER-0000000004 (stores: [])
      --> KSTREAM-JOIN-0000000005
      <-- KSTREAM-SOURCE-0000000003
    Processor: KSTREAM-JOIN-0000000005 (stores: [table-STATE-STORE-0000000000])
      --> KSTREAM-SINK-0000000006
      <-- KSTREAM-FILTER-0000000004
    Source: KSTREAM-SOURCE-0000000001 (topics: [table])
      --> KTABLE-SOURCE-0000000002
    Sink: KSTREAM-SINK-0000000006 (topic: output)
      <-- KSTREAM-JOIN-0000000005
    Processor: KTABLE-SOURCE-0000000002 (stores: [table-STATE-STORE-0000000000])
      --> none
      <-- KSTREAM-SOURCE-0000000001
```

A sample project is available at https://github.com/metcox/brave-kafka-streams-topology.git

### PR DESCRIPTION
**Pull request by jeqo**
Fixes #942 

Some Kafka Streams instrumented operations are implemented by using `Transformer` API that, **if followed by grouping or joining**, causes re-partitioning (new topic to store data with potentially new key).

Operations affected:
- `peek`
- `mark`

**Filter:**

`filter` and `filterNot` are a special case, as if they are changed to `ValueTransformerWithKey` will anyway emit a `KeyValue` with `value=null` downstream, breaking the filtering.

CC @jorgheymans

### CODE REVIEW

File: instrumentation/kafka-streams/src/test/java/brave/kafka/streams/ITKafkaStreamsTracing.java [hunk 1]
```diff
@@ -284,13 +284,16 @@ public void should_create_spans_from_stream_with_tracing_filter_predicate_false(
...
-  public void should_create_spans_from_stream_with_tracing_filternot_predicate_true() throws Exception {
+  public void should_create_spans_from_stream_with_tracing_filter_not_predicate_true() throws Exception {
     String inputTopic = testName.getMethodName() + "-input";
     String outputTopic = testName.getMethodName() + "-output";
 
     StreamsBuilder builder = new StreamsBuilder();
     builder.stream(inputTopic, Consumed.with(Serdes.String(), Serdes.String()))
         .transform(kafkaStreamsTracing.filterNot("filterNot-1", (key, value) -> true))
+        .peek((s, s2) -> {
+          System.out.println(s + "-" + s2);
```
Comment (jorgheymans) [inline instrumentation/kafka-streams/src/test/java/brave/kafka/streams/ITKafkaStreamsTracing.java]: Accidentally committed the System.out ?

Comment (jeqo) [reply instrumentation/kafka-streams/src/test/java/brave/kafka/streams/ITKafkaStreamsTracing.java]: hehe yes! thanks :)

File: instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java [hunk 2]
```diff
@@ -283,6 +283,46 @@ public KafkaStreams kafkaStreams(Topology topology, Properties streamsConfig) {
     return new TracingFilterTransformerSupplier<>(this, spanName, predicate, true);
   }
 
+  /**
+   * Create a markFilter valueTransformer.
```
Comment (jorgheymans) [inline instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java]: Not too sold on `markFilter` as a name. The other filter implementation also marks the span as filtered or not so that would not be the distinguishing feature. Having said that, i'm also struggling to find a fitting name :/ 

`filterValues` , `filterNotValues` to indicate that it goes with a ValueTransformer perhaps, not that great either.

File: instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java [hunk 3]
```diff
@@ -244,6 +247,10 @@ public KafkaStreams kafkaStreams(Topology topology, Properties streamsConfig) {
 
   /**
    * Create a filter transformer.
+   *
+   * WARNING: as this filter is based on Transformer API, if followed by a grouping or joining
```
Comment (jorgheymans) [inline instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java]: Maybe a bit more elaborate like

> WARNING: this filter implementation uses the Streams <a href="https://kafka.apache.org/22/javadoc/org/apache/kafka/streams/kstream/KStream.html#transform-org.apache.kafka.streams.kstream.TransformerSupplier-java.lang.String...-}">transform</a> API, meaning that re-partitioning can occur if a key modifying operation like grouping or joining operation is applied after this filter. In that case, consider using {link #markFilter} instead which uses <a href="https://kafka.apache.org/22/javadoc/org/apache/kafka/streams/kstream/KStream.html#transformValues-org.apache.kafka.streams.kstream.ValueTransformerSupplier-java.lang.String...-">transformValues</a> API instead.


(javadoc links might be not correct but you get the idea)

File: instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java [hunk 4]
```diff
@@ -259,6 +266,10 @@ public KafkaStreams kafkaStreams(Topology topology, Properties streamsConfig) {
 
   /**
    * Create a filterNot transformer.
+   *
```
Comment (jorgheymans) [inline instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java]: same as above javadoc suggestion

**Comment by adriancole** [comment]
good one!

File: instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java (hunk 2 above)
Comment (jeqo) [reply instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java]: yeap, I don't think naming it `filterValues` and having to actually `filter` later is a good user experience :(

Just pick `markFilter` as seems similar to current `mark` function purpose.

Comment (jeqo) [reply instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java]: @jorgheymans what about `markIsFiltered`/`markIsNotFiltered` ?
